// Code generated by hertz generator.

package main

import (
	handler "douyin/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	apiRouter := r.Group("/douyin")
	apiRouter.POST("/user/register/", handler.Register)
	// your code ...
}
